version: "3.9"
services:
  mqtt:
    build: mqtt_broker
    ports:
      - "1883:1883"
    restart: always
    networks:
      - backend
  database:
      image: influxdb:latest
      ports:
        - "8086:8086"
      restart: always
      volumes:
          - influxdb_volume:/var/lib/influxdb
      networks:
        - backend
      environment:
        - DOCKER_INFLUXDB_INIT_MODE=setup
        - DOCKER_INFLUXDB_INIT_USERNAME=admin
        - DOCKER_INFLUXDB_INIT_PASSWORD=password
        - DOCKER_INFLUXDB_INIT_ORG=press_play
        - DOCKER_INFLUXDB_INIT_BUCKET=telegraf_data
        - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=oursecrettoken
  telegraf:
      build: telegraf_instance
      restart: always
      networks:
        - backend
volumes:
  influxdb_volume:


networks:
  backend:
    driver: bridge


